// <auto-generated />
namespace DesignUrFixie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TakeThree : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TakeThree));
        
        string IMigrationMetadata.Id
        {
            get { return "201607212018005_TakeThree"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
